# Generated by Django 5.2.7 on 2025-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_sitedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
    ]
