# Generated by Django 5.2.7 on 2025-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_latitude_alter_customuser_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedocument',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
