# Generated by Django 5.2.7 on 2025-12-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_sitedocument_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedocument',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
