# Generated by Django 5.1.6 on 2025-02-22 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joker_chat', '0003_friendship_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Display name must end with "_bot"', regex='.*_bot$')])),
                ('poziom', models.IntegerField(default=1)),
                ('opis', models.TextField(blank=True, max_length=150)),
                ('endpoint', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
