# Generated by Django 5.1.6 on 2025-02-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joker_chat', '0004_bots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bots',
        ),
    ]
