# Generated by Django 5.1.6 on 2025-02-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joker_chat', '0005_delete_bots'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='friend_message',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
