# Generated by Django 5.1.6 on 2025-02-24 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joker_chat', '0009_alter_message_room_name_alter_message_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='nadawca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nadawca', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='odbiorca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='odbiorca', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
