# Generated by Django 5.1.6 on 2025-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joker_chat', '0010_remove_message_room_name_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='last_view_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
